#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.10.3.build{build}

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      ARCH: "32"
      
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64
      ARCH: "64"

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda install --quiet conda
  - conda info --all
  - conda create -n _polite python=2.7 pip
  - activate _polite
  - conda install --file requirements-conda-dev.txt
  - pip install -e .
  - conda install mock pytest pytest-cov pytest-mock

build: off

test_script:
  - py.test --cov=polite tests

after_test:
 - pip install codecov
 - codecov
